name: Launch EC2
on: [push]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: display files 
        run: ls -la

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: init 
        run: terraform init 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: plan 
        run: terraform plan