name: Launch EC2
on: [push]
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: display files 
        run: ls -la

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: init 
        run: terraform init 